### ISSUE TITLE
err = scalar or array in the convergence_rates function

### ISSUE THREAD

**Issue by JouvalSomer** [MATMEK-4270/mandatory1#1]
In the given code for the wave equation [('Wave2D')](https://github.com/MATMEK-4270/matmek4270-mandatory1/blob/8bd2e43ac8ab2df733b397c73f99b82493b90615/Wave2D.py#L9) in the convergence_rates function the l2 error is append to a list E as follows:

            dx, err = self(N0, Nt, cfl=cfl, mx=mx, my=my, store_data=-1)
            E.append(err[-1]).

Should err here be an array or a scalar? For me it is a scalar so I get an IndexError, thats why I am asking.

**Comment by mikaem** [comment]
Hi
Thank you for using the issue tracker:-)
The wave problem is time dependent and there can as such be one l2-error computed for each time step. The `convergence_rates` function makes use of the l2-error from the last time step. Hence err[-1]. Implement `__call__` such that it computes the l2-error norm each time step and return an array or list of errors. Then it should work:-)

**Comment by JouvalSomer** [comment]
OK, I just have my `__call__` method only return the error for the last time step as seen below. Snippet from the end of the `__call__` method: 
        
        if store_data > 0:
            return stored_data
        else:
            err = self.l2_error(Unp1, Nt*dt)
            return self.h, err

where Unp1 is the solution form the last iteration. Is that fine as well?

**Comment by mikaem** [comment]
It will work just fine with the `convergence_rates` method if you use 

    if store_data > 0:
        return stored_data
    else:
        err = self.l2_error(Unp1, Nt*dt)
        return self.h, [err]

**Comment by JouvalSomer** [comment]
Yes, of course:) Thanks!
