### ISSUE TITLE
Lagrange interpolation in poisson2d

### ISSUE THREAD

**Issue by karensamseth** [MATMEK-4270/mandatory1#2]
Are we supposed to write all the code for Lagrange interpolation as you did in lecture 7? I found there is a function scipy.interpolate.lagrange. Is it all right to just use that? 

If ok with scipy function: for me it looks like it is used for 1D case, so how to make it 2d?

If not: I have a problem with having with finding the points we want to evaluate in to make the Lagrange basis, as the point in the test is so close to the edge. We should use Lagrange for more than two points in each direction, right?

**Comment by mikaem** [comment]
Yes, you can use the function `scipy.interpolate.lagrange`, but it is only for 1d. So you need to implement something like [here](https://matmek-4270.github.io/matmek4270-book/lecture7.html#equation-eq-lagrange), with one function for the x-direction and another for the y-direction.

One point is chosen to be very close to the border. This is not a problem, you just need to find out which cell the point is in and then I think using the four points of the cell for interpolation will do. Like in the Figure below [here](https://matmek-4270.github.io/matmek4270-book/lecture7.html#equation-eq-lagrange) if the red dot was in a cell closest to a border.
